app:
  port: 8888

datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: sqlcheck
  username: root
  password: q10010
  charset: utf8mb4

goinception:
  host: 127.0.0.1
  port: 4000
  rollbakdb_host: 127.0.0.1
  rollbakdb_port: 3306
  rollbakdb_passwd: q10010
  rollbakdb_user: root